/**:
  ros__parameters:
    # 轮子参数
    wheel_radius: 0.15
    wheelbase_x: 0.75
    wheelbase_y: 0.5

    # 速度限制
    max_velocity: 1.0
    max_angular: 1.0

    # 坐标系
    odom_frame: 'odom'
    base_frame: 'base_link'

    # 模式
    use_sim: false